import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const CURRENT_YEAR = new Date().getFullYear();
const YEARS = Array.from({ length: 15 }, (_, i) => CURRENT_YEAR - i);
const QUALITIES = ['HD', '4K', 'SD'];
export default function FilterBar({ value, onChange, showQuality = false, genres = [], }) {
    const handleChange = (key, val) => {
        onChange({
            ...value,
            [key]: val === '' ? undefined : key === 'year' ? Number(val) : val,
            page: 1,
        });
    };
    return (_jsxs("div", { className: "flex flex-wrap gap-3 mb-6", children: [_jsxs("select", { value: ('genreId' in value && value.genreId) || '', onChange: (e) => handleChange('genreId', e.target.value), className: "bg-[#1a1a24] border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white focus:outline-none focus:border-[#e50914]/50", "aria-label": "Filtrer par genre", children: [_jsx("option", { value: "", children: "Tous les genres" }), genres.map((g) => (_jsx("option", { value: g.id, children: g.name }, g.id)))] }), _jsxs("select", { value: value.year ?? '', onChange: (e) => handleChange('year', e.target.value), className: "bg-[#1a1a24] border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white focus:outline-none focus:border-[#e50914]/50", "aria-label": "Filtrer par ann\u00E9e", children: [_jsx("option", { value: "", children: "Toutes les ann\u00E9es" }), YEARS.map((y) => (_jsx("option", { value: y, children: y }, y)))] }), _jsxs("select", { value: value.availability ?? '', onChange: (e) => handleChange('availability', e.target.value), className: "bg-[#1a1a24] border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white focus:outline-none focus:border-[#e50914]/50", "aria-label": "Filtrer par disponibilit\u00E9", children: [_jsx("option", { value: "", children: "Toutes disponibilit\u00E9s" }), _jsx("option", { value: "AVAILABLE", children: "Disponibles" }), _jsx("option", { value: "UNAVAILABLE", children: "Non disponibles" })] }), _jsxs("select", { value: value.sortBy ?? '', onChange: (e) => handleChange('sortBy', e.target.value), className: "bg-[#1a1a24] border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white focus:outline-none focus:border-[#e50914]/50", "aria-label": "Trier par", children: [_jsx("option", { value: "", children: "Tri : titre" }), _jsx("option", { value: "title", children: "Titre" }), _jsx("option", { value: "year", children: "Ann\u00E9e" }), _jsx("option", { value: "recentAvailability", children: "R\u00E9cemment disponible" })] }), showQuality && (_jsxs("select", { value: ('quality' in value && value.quality) || '', onChange: (e) => handleChange('quality', e.target.value), className: "bg-[#1a1a24] border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white focus:outline-none focus:border-[#e50914]/50", "aria-label": "Filtrer par qualit\u00E9", children: [_jsx("option", { value: "", children: "Toutes les qualit\u00E9s" }), QUALITIES.map((q) => (_jsx("option", { value: q, children: q }, q)))] }))] }));
}
//# sourceMappingURL=FilterBar.js.map