const LANGUAGE_NAMES: Record<string, string> = {
  fr: 'Français',
  fre: 'Français',
  fra: 'Français',
  en: 'English',
  eng: 'English',
  de: 'Deutsch',
  ger: 'Deutsch',
  deu: 'Deutsch',
  es: 'Español',
  spa: 'Español',
  it: 'Italiano',
  ita: 'Italiano',
  pt: 'Português',
  por: 'Português',
  ru: 'Русский',
  rus: 'Русский',
  ar: 'العربية',
  ara: 'العربية',
  zh: '中文',
  chi: '中文',
  zho: '中文',
  ja: '日本語',
  jpn: '日本語',
  ko: '한국어',
  kor: '한국어',
  nl: 'Nederlands',
  nld: 'Nederlands',
  dut: 'Nederlands',
  pl: 'Polski',
  pol: 'Polski',
  sv: 'Svenska',
  swe: 'Svenska',
  da: 'Dansk',
  dan: 'Dansk',
  no: 'Norsk',
  nor: 'Norsk',
  fi: 'Suomi',
  fin: 'Suomi',
  tr: 'Türkçe',
  tur: 'Türkçe',
  cs: 'Čeština',
  ces: 'Čeština',
  cze: 'Čeština',
  sk: 'Slovenčina',
  slk: 'Slovenčina',
  hu: 'Magyar',
  hun: 'Magyar',
  ro: 'Română',
  ron: 'Română',
  rum: 'Română',
  el: 'Ελληνικά',
  ell: 'Ελληνικά',
  gre: 'Ελληνικά',
  he: 'עברית',
  heb: 'עברית',
  th: 'ภาษาไทย',
  tha: 'ภาษาไทย',
  vi: 'Tiếng Việt',
  vie: 'Tiếng Việt',
  hi: 'हिन्दी',
  hin: 'हिन्दी',
  und: 'Indéfini',
}

export function getLanguageName(code: string | null | undefined): string {
  if (!code) return 'Indéfini'
  const key = code.toLowerCase()
  return LANGUAGE_NAMES[key] ?? code.toUpperCase()
}
